// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBX9ysDZB7J6qXcCkCAaH17guIxXVVfeU',
    appId: '1:770391039672:web:b602e7e5ee2b0e67ed5e4d',
    messagingSenderId: '770391039672',
    projectId: 'petpilot-379703',
    authDomain: 'petpilot-379703.firebaseapp.com',
    storageBucket: 'petpilot-379703.appspot.com',
    measurementId: 'G-T38X92DZHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQfnTCJ7dSIe5QuZAKS6j07ZpT5oL-86w',
    appId: '1:770391039672:android:9dca73429db49c81ed5e4d',
    messagingSenderId: '770391039672',
    projectId: 'petpilot-379703',
    storageBucket: 'petpilot-379703.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN2FzxRkVGHw2nTMzTPyNTIxsXP-cqQd8',
    appId: '1:770391039672:ios:013c3dc653941942ed5e4d',
    messagingSenderId: '770391039672',
    projectId: 'petpilot-379703',
    storageBucket: 'petpilot-379703.appspot.com',
    iosClientId: '770391039672-ltm4lsalu0ro8bd6mioq14go9bsspi5v.apps.googleusercontent.com',
    iosBundleId: 'com.pawporation.petpilot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN2FzxRkVGHw2nTMzTPyNTIxsXP-cqQd8',
    appId: '1:770391039672:ios:d89742f6f310d90ced5e4d',
    messagingSenderId: '770391039672',
    projectId: 'petpilot-379703',
    storageBucket: 'petpilot-379703.appspot.com',
    iosClientId: '770391039672-co8ds04cgq8ikpmqffjt8gdklanjrqlg.apps.googleusercontent.com',
    iosBundleId: 'com.pawporation.petpilot.RunnerTests',
  );
}
